package actions

import (
	//"os/user"
	"encoding/json"
	"fmt"
	"github.com/desylva/movienight/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	//"database/sql"
	// "fmt"
	// "github.com/desylva/movienight/models"
	// "github.com/gobuffalo/buffalo/render"
	// "github.com/gobuffalo/packr"
	// "github.com/gobuffalo/plush"
	// "github.com/gobuffalo/pop"
	"github.com/gobuffalo/envy"
	"github.com/gobuffalo/pop/nulls"
	"log"
)

var OMDB_API_KEY = envy.Get("OMDB_API_KEY", "nothing")
var OMDB_URL = "http://www.omdbapi.com/"

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Movie)
// DB Table: Plural (movies)
// Resource: Plural (Movies)
// Path: Plural (/movies)
// View Template Folder: Plural (/templates/movies/)

// MoviesResource is the resource for the Movie model
type MoviesResource struct {
	buffalo.Resource
}

// List gets all Movies. This function is mapped to the path
// GET /movies
func (v MoviesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	movies := &models.Movies{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Movies from the DB
	if err := q.All(movies); err != nil {
		return errors.WithStack(err)
	}

	// for _, m := range *movies {
	// 	&m.ImdbData = getMovieData(ImdbIDString(m.Imdb))
	// }

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, movies))
}

// Show gets the data for one Movie. This function is mapped to
// the path GET /movies/{movie_id}
func (v MoviesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Movie
	movie := &models.Movie{}

	// To find the Movie the parameter movie_id is used.
	if err := tx.Find(movie, c.Param("movy_id")); err != nil {
		return c.Error(404, err)
	}

	ImdbData := OMDBMovieData(ImdbIDString(movie.Imdb))

	c.Set("ImdbData", ImdbData)
	return c.Render(200, r.Auto(c, movie))
}

// New renders the form for creating a new Movie.
// This function is mapped to the path GET /movies/new
func (v MoviesResource) New(c buffalo.Context) error {
	c.Set("title", "")
	return c.Render(200, r.Auto(c, &models.Movie{}))
}

func trimQuotes(s string) string {
	if len(s) >= 2 {
		if s[0] == '"' && s[len(s)-1] == '"' {
			return s[1 : len(s)-1]
		}
	}
	return s
}

// Create adds a Movie to the DB. This function is mapped to the
// path POST /movies
func (v MoviesResource) Create(c buffalo.Context) error {
	// Allocate an empty Movie
	movie := &models.Movie{}

	// Bind movie to the html form elements
	if err := c.Bind(movie); err != nil {
		return errors.WithStack(err)
	}

	userId, ok := c.Session().Get("current_user_id").(string)
	if !ok {
		return errors.New("Couldn't convert user id")
	}
	movie.UserUUID = userId

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(movie)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, movie))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Movie was created successfully")

	// and redirect to the movies index page
	return c.Render(201, r.Auto(c, movie))
}

// Edit renders a edit form for a Movie. This function is
// mapped to the path GET /movies/{movie_id}/edit
func (v MoviesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Movie
	movie := &models.Movie{}

	if err := tx.Find(movie, c.Param("movy_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, movie))
}

// Update changes a Movie in the DB. This function is mapped to
// the path PUT /movies/{movie_id}
func (v MoviesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Movie
	movie := &models.Movie{}

	if err := tx.Find(movie, c.Param("movy_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Movie to the html form elements
	if err := c.Bind(movie); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(movie)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, movie))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Movie was updated successfully")

	// and redirect to the movies index page
	return c.Render(200, r.Auto(c, movie))
}

// Destroy deletes a Movie from the DB. This function is mapped
// to the path DELETE /movies/{movie_id}
func (v MoviesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Movie
	movie := &models.Movie{}

	// To find the Movie the parameter movie_id is used.
	if err := tx.Find(movie, c.Param("movy_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(movie); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Movie was destroyed successfully")

	// Redirect to the movies index page
	return c.Render(200, r.Auto(c, movie))
}

func ImdbIDString(imdbID nulls.String) string {
	imdbByte, _ := imdbID.MarshalJSON()
	return trimQuotes(string(imdbByte))
}

// OMDBSearch makes a request to OMDB and attempt to retrieve
// a movie.
func OMDBSearch(c buffalo.Context) error {
	data := models.ImdbData{}

	title := c.Request().FormValue("title")
	title = url.QueryEscape(title)

	s := []string{OMDB_URL, "?t=", title, "&apikey=", OMDB_API_KEY}
	link := fmt.Sprintf(strings.Join(s, ""))

	resp, err := http.Get(link)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		json.Unmarshal(bodyBytes, &data)
		//log.Printf("%+v", data)
	}
	c.Set("movie", data)
	return c.Render(200, r.JavaScript("search.js"))
}

// OMDBMovieData makes a request to OMDB to retrieve the details
// of a movie from its unique tt id
func OMDBMovieData(imdbID string) models.ImdbData {
	data := models.ImdbData{}

	s := []string{OMDB_URL, "?i=", imdbID, "&apikey=", OMDB_API_KEY}
	link := fmt.Sprintf(strings.Join(s, ""))

	resp, err := http.Get(link)
	if err != nil {
		return data
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusOK {
		bodyBytes, _ := ioutil.ReadAll(resp.Body)
		json.Unmarshal(bodyBytes, &data)
		log.Printf("%+v", data)
	}

	return data
}

//{"Title":"Johnny English Strikes Again","Year":"2018","Rated":"PG",
//"Released":"26 Oct 2018","Runtime":"88 min",
//"Genre":"Action, Adventure, Comedy",
//"Director":"David Kerr","Writer":"William Davies (screenplay by)",
//"Actors":"Olga Kurylenko, Rowan Atkinson, Emma Thompson, Charles Dance",
//"Plot":"After a cyber-attack reveals the identity of all of the active undercover agents
//in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.",
//"Language":"English","Country":"UK, France, USA","Awards":"N/A",
//"Poster":"https://m.media-amazon.com/images/M/MV5BMjI4MjQ3MjI5MV5BMl5BanBnXkFtZTgwNjczMDE4NTM@._V1_SX300.jpg",
//"Ratings":[{"Source":"Internet Movie Database","Value":"6.6/10"},
//{"Source":"Rotten Tomatoes","Value":"37%"},{"Source":"Metacritic","Value":"35/100"}],
//"Metascore":"35","imdbRating":"6.6","imdbVotes":"9,960","imdbID":"tt6921996",
//"Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"Universal Pictures",
//"Website":"http://www.johnnyenglishmovie.com/","Response":"True"}
